# schema.yml
version: 2
models:
  - name: "orders"
    description: "A table of all orders."
    columns:
      - name: "customer_id"
      - name: "first_name"
      - name: "last_name"
      - name: "status"
        description: "Status of an order: ordered/processed/complete"
      - name: "first_order_date"
      - name: "most_recent_order_date"
      - name: "order_date"
      - name: "status"
      - name: "qty"
        meta:
          metrics:
            quantity:
              type: sum
      - name: "unit_price"
        meta:
          metrics:
            unit_price:
              type: sum
      - name: "order_id"
        meta:
          metrics:
            order_count:
              type: count
      - name: "order_total"
        meta:
          metrics:
            order_total:
              type: sum




#customer_id	INTEGER	NULLABLE		
#first_name	STRING	NULLABLE		
#last_name	STRING	NULLABLE		
#first_order_date	DATE	NULLABLE		
#most_recent_order_date	DATE	NULLABLE		
#order_date	DATE	NULLABLE		
#qty	INTEGER	NULLABLE		
#unit_price	FLOAT	NULLABLE		
#order_total	FLOAT	NULLABLE